[package]
name = "correct-example"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.47.1", features = ["macros", "time", "rt-multi-thread", "sync"] }
env_logger = "0.11"
log = "0.4"
